import type {
  Assessment,
  Batch,
  DashboardData,
  ModuleItem,
  PaymentRecord,
  Program,
  ResourceItem,
  ResultRecord,
  StudentProfile,
  Testimonial,
} from "@/lib/types";

export const demoPrograms: Program[] = [
  {
    id: "program-theory",
    slug: "theory",
    name: "Theory",
    shortName: "Theory",
    description: "Complete ICT theory lessons with structured notes and steady syllabus coverage.",
    academicLevel: "O/L",
    examYear: null,
    medium: ["Sinhala", "English"],
    image: "/ol-theory-poster.jpg",
    isPublic: true,
    registrationOpen: true,
    isActive: true,
  },
  {
    id: "program-revision",
    slug: "revision",
    name: "Revision",
    shortName: "Revision",
    description: "Focused syllabus revision with targeted practice and regular assessment.",
    academicLevel: "O/L",
    examYear: null,
    medium: ["Sinhala", "English"],
    image: "/ol-theory-poster.jpg",
    isPublic: true,
    registrationOpen: true,
    isActive: true,
  },
  {
    id: "program-paper",
    slug: "paper",
    name: "Paper",
    shortName: "Paper",
    description: "Past-paper practice, answering technique and detailed paper discussion.",
    academicLevel: "O/L",
    examYear: null,
    medium: ["Sinhala", "English"],
    image: "/ol-theory-poster.jpg",
    isPublic: true,
    registrationOpen: true,
    isActive: true,
  },
  {
    id: "program-rapid-revision",
    slug: "rapid-revision",
    name: "Rapid Revision",
    shortName: "Rapid Revision",
    description: "Fast, exam-oriented revision with intensive paper practice.",
    academicLevel: "O/L",
    examYear: null,
    medium: ["Sinhala", "English"],
    image: "/rapid-revision-poster.jpg",
    isPublic: true,
    registrationOpen: true,
    isActive: true,
  },
];

export const demoBatches: Batch[] = [
  { id: "batch-theory-2026", programId: "program-theory", name: "2026 O/L", isActive: true },
  { id: "batch-theory-2027", programId: "program-theory", name: "2027 O/L", isActive: true },
  { id: "batch-revision-2026", programId: "program-revision", name: "2026 O/L", isActive: true },
  { id: "batch-revision-2027", programId: "program-revision", name: "2027 O/L", isActive: true },
  { id: "batch-paper-2026", programId: "program-paper", name: "2026 O/L", isActive: true },
  { id: "batch-paper-2027", programId: "program-paper", name: "2027 O/L", isActive: true },
  { id: "batch-rapid-2026", programId: "program-rapid-revision", name: "2026 O/L", isActive: true },
  { id: "batch-rapid-2027", programId: "program-rapid-revision", name: "2027 O/L", isActive: true },
];

export const demoStudent: StudentProfile = {
  id: "student-demo-001",
  firstName: "Nethmi",
  lastName: "Perera",
  fullName: "Nethmi Perera",
  phone: "94771234567",
  dateOfBirth: "2010-04-16",
  nic: null,
  address: "Minuwangoda, Sri Lanka",
  school: "President's College, Minuwangoda",
  medium: "English",
  role: "student",
  accountStatus: "verified",
  createdAt: "2026-06-10T08:30:00.000Z",
  programIds: ["program-theory"],
  batchIds: ["batch-theory-2026"],
};

export const demoStudents: StudentProfile[] = [
  demoStudent,
  {
    ...demoStudent,
    id: "student-demo-002",
    firstName: "Kavindu",
    lastName: "Fernando",
    fullName: "Kavindu Fernando",
    phone: "94774561234",
    medium: "Sinhala",
    accountStatus: "pending",
    programIds: [],
    batchIds: [],
    school: "Nalanda Boys' Central College",
  },
  {
    ...demoStudent,
    id: "student-demo-003",
    firstName: "Senali",
    lastName: "Jayasinghe",
    fullName: "Senali Jayasinghe",
    phone: "94775678901",
    medium: "Sinhala",
    accountStatus: "verified",
    programIds: ["program-theory"],
    batchIds: ["batch-theory-2027"],
    school: "Minuwangoda Central College",
  },
];

export const demoResources: ResourceItem[] = [
  {
    id: "resource-number-systems",
    moduleId: "module-july-2026",
    title: "Number Systems — Smart Summary",
    description: "A concise summary sheet covering binary, octal, decimal and hexadecimal conversions.",
    fileName: "number-systems-smart-summary.pdf",
    fileUrl: "#",
    fileType: "PDF",
    access: "free",
    publishedAt: "2026-07-02T08:00:00.000Z",
    programIds: ["program-theory"],
    batchIds: [],
  },
  {
    id: "resource-programming-tute",
    moduleId: "module-july-2026",
    title: "Programming Revision Tute 01",
    description: "Flowcharts, algorithms and introductory programming questions for guided practice.",
    fileName: "programming-revision-tute-01.pdf",
    fileUrl: "#",
    fileType: "Tute",
    access: "paid",
    publishedAt: "2026-07-08T10:00:00.000Z",
    programIds: ["program-theory"],
    batchIds: ["batch-theory-2026"],
  },
  {
    id: "resource-spreadsheet",
    moduleId: "module-june-2026",
    title: "Spreadsheet Formula Sheet",
    description: "Essential spreadsheet functions, references and examples in one printable sheet.",
    fileName: "spreadsheet-formula-sheet.pdf",
    fileUrl: "#",
    fileType: "Worksheet",
    access: "paid",
    publishedAt: "2026-06-18T10:00:00.000Z",
    programIds: ["program-theory"],
    batchIds: ["batch-theory-2026"],
  },
  {
    id: "resource-free-model",
    moduleId: null,
    title: "Free ICT Model MCQ Paper",
    description: "A free 40-question MCQ paper for every registered Smart ICT student.",
    fileName: "free-model-mcq-paper.pdf",
    fileUrl: "#",
    fileType: "Past Paper",
    access: "free",
    publishedAt: "2026-07-10T14:00:00.000Z",
    programIds: [],
    batchIds: [],
  },
];

export const demoAssessments: Assessment[] = [
  {
    id: "assessment-diagnostic-01",
    moduleId: "module-july-2026",
    title: "ICT Diagnostic Assessment 01",
    description: "A short diagnostic paper covering core concepts from data representation, programming and spreadsheets.",
    instructions: "Answer every question. Your answers are saved automatically. Review flagged questions before submitting.",
    delivery: "online",
    timing: "flexible",
    source: "smart_ict",
    status: "published",
    durationMinutes: 20,
    startsAt: "2026-07-01T00:00:00.000Z",
    endsAt: "2026-07-31T18:30:00.000Z",
    maxAttempts: 1,
    shuffleQuestions: false,
    shuffleOptions: false,
    showAnswers: true,
    showResults: true,
    access: "free",
    totalMarks: 10,
    programIds: ["program-theory"],
    batchIds: [],
    studentIds: [],
    questions: [
      {
        id: "q1",
        type: "single_choice",
        prompt: "Which number system uses the digits 0 to 7?",
        marks: 1,
        options: [
          { id: "q1a", key: "A", text: "Binary" },
          { id: "q1b", key: "B", text: "Octal" },
          { id: "q1c", key: "C", text: "Decimal" },
          { id: "q1d", key: "D", text: "Hexadecimal" },
        ],
        correctAnswer: "B",
        explanation: "The octal number system has base 8 and uses digits 0 through 7.",
      },
      {
        id: "q2",
        type: "single_choice",
        prompt: "What is the decimal value of binary 1010?",
        marks: 1,
        options: [
          { id: "q2a", key: "A", text: "8" },
          { id: "q2b", key: "B", text: "9" },
          { id: "q2c", key: "C", text: "10" },
          { id: "q2d", key: "D", text: "12" },
        ],
        correctAnswer: "C",
        explanation: "1010₂ = 8 + 2 = 10₁₀.",
      },
      {
        id: "q3",
        type: "true_false",
        prompt: "A flowchart is a graphical representation of an algorithm.",
        marks: 1,
        options: [
          { id: "q3a", key: "True", text: "True" },
          { id: "q3b", key: "False", text: "False" },
        ],
        correctAnswer: "True",
        explanation: "Flowcharts use standard symbols to show the sequence and logic of an algorithm.",
      },
      {
        id: "q4",
        type: "single_choice",
        prompt: "Which spreadsheet formula correctly adds cells A1 to A5?",
        marks: 1,
        options: [
          { id: "q4a", key: "A", text: "=ADD(A1:A5)" },
          { id: "q4b", key: "B", text: "=SUM(A1:A5)" },
          { id: "q4c", key: "C", text: "SUM=A1:A5" },
          { id: "q4d", key: "D", text: "=TOTAL(A1-A5)" },
        ],
        correctAnswer: "B",
        explanation: "SUM is the standard spreadsheet function for adding a range of cells.",
      },
      {
        id: "q5",
        type: "single_choice",
        prompt: "What is the final value of x? x = 4; x = x + 3; x = x * 2",
        marks: 1,
        options: [
          { id: "q5a", key: "A", text: "10" },
          { id: "q5b", key: "B", text: "11" },
          { id: "q5c", key: "C", text: "14" },
          { id: "q5d", key: "D", text: "16" },
        ],
        correctAnswer: "C",
        explanation: "x becomes 7 after addition, and 7 × 2 gives 14.",
      },
      {
        id: "q6",
        type: "single_choice",
        prompt: "Which device is commonly used to connect multiple computers within a LAN?",
        marks: 1,
        options: [
          { id: "q6a", key: "A", text: "Switch" },
          { id: "q6b", key: "B", text: "Scanner" },
          { id: "q6c", key: "C", text: "Plotter" },
          { id: "q6d", key: "D", text: "Projector" },
        ],
        correctAnswer: "A",
        explanation: "A network switch connects devices inside a local area network.",
      },
      {
        id: "q7",
        type: "true_false",
        prompt: "RAM keeps its data permanently after the power is switched off.",
        marks: 1,
        options: [
          { id: "q7a", key: "True", text: "True" },
          { id: "q7b", key: "False", text: "False" },
        ],
        correctAnswer: "False",
        explanation: "RAM is volatile memory, so its contents are lost when power is removed.",
      },
      {
        id: "q8",
        type: "single_choice",
        prompt: "Which HTML element creates a hyperlink?",
        marks: 1,
        options: [
          { id: "q8a", key: "A", text: "<p>" },
          { id: "q8b", key: "B", text: "<a>" },
          { id: "q8c", key: "C", text: "<img>" },
          { id: "q8d", key: "D", text: "<table>" },
        ],
        correctAnswer: "B",
        explanation: "The anchor element <a> is used to create hyperlinks.",
      },
      {
        id: "q9",
        type: "single_choice",
        prompt: "Which stage of the system development life cycle identifies user requirements?",
        marks: 1,
        options: [
          { id: "q9a", key: "A", text: "Analysis" },
          { id: "q9b", key: "B", text: "Implementation" },
          { id: "q9c", key: "C", text: "Maintenance" },
          { id: "q9d", key: "D", text: "Testing" },
        ],
        correctAnswer: "A",
        explanation: "Requirements are gathered and analysed during the analysis stage.",
      },
      {
        id: "q10",
        type: "single_choice",
        prompt: "Which field uniquely identifies each record in a database table?",
        marks: 1,
        options: [
          { id: "q10a", key: "A", text: "Foreign key" },
          { id: "q10b", key: "B", text: "Primary key" },
          { id: "q10c", key: "C", text: "Data type" },
          { id: "q10d", key: "D", text: "Query" },
        ],
        correctAnswer: "B",
        explanation: "A primary key uniquely identifies every record in a table.",
      },
    ],
  },
  {
    id: "assessment-july-paper",
    moduleId: "module-july-2026",
    title: "July Monthly Paper",
    description: "A complete monthly paper released to paid students in the 2026 O/L programme.",
    instructions: "Complete the paper within the allocated time. Results will be released after the closing time.",
    delivery: "online",
    timing: "strict",
    source: "smart_ict",
    status: "published",
    durationMinutes: 45,
    startsAt: "2026-07-20T13:30:00.000Z",
    endsAt: "2026-07-20T14:15:00.000Z",
    maxAttempts: 1,
    shuffleQuestions: true,
    shuffleOptions: true,
    showAnswers: false,
    showResults: false,
    access: "paid",
    totalMarks: 40,
    programIds: ["program-theory"],
    batchIds: ["batch-theory-2026"],
    studentIds: [],
    questions: [],
  },
  {
    id: "assessment-school-term-2",
    moduleId: null,
    title: "School Second Term Examination",
    description: "Offline school examination result uploaded to keep the complete academic journey in one place.",
    instructions: "Offline result record.",
    delivery: "offline",
    timing: "flexible",
    source: "school",
    status: "published",
    durationMinutes: null,
    startsAt: null,
    endsAt: null,
    maxAttempts: 1,
    shuffleQuestions: false,
    shuffleOptions: false,
    showAnswers: false,
    showResults: true,
    access: "paid",
    totalMarks: 100,
    programIds: ["program-theory"],
    batchIds: [],
    studentIds: [],
    questions: [],
  },
];

export const demoModules: ModuleItem[] = [
  {
    id: "module-may-2026",
    programId: "program-theory",
    batchId: "batch-theory-2026",
    title: "May 2026",
    month: 5,
    year: 2026,
    access: "paid",
    status: "published",
    opensAt: "2026-05-01T00:00:00.000Z",
    closesAt: null,
    recordings: [
      {
        id: "rec-may-01",
        moduleId: "module-may-2026",
        title: "Data Representation — Complete Revision",
        description: "Number systems, character representation and data units.",
        videoUrl: "#",
        publishedAt: "2026-05-05T12:00:00.000Z",
        access: "paid",
        duration: "1h 42m",
      },
    ],
    resources: [],
    assessmentIds: [],
  },
  {
    id: "module-june-2026",
    programId: "program-theory",
    batchId: "batch-theory-2026",
    title: "June 2026",
    month: 6,
    year: 2026,
    access: "paid",
    status: "published",
    opensAt: "2026-06-01T00:00:00.000Z",
    closesAt: null,
    recordings: [
      {
        id: "rec-june-01",
        moduleId: "module-june-2026",
        title: "Spreadsheets — Functions and References",
        description: "Formula writing, common functions and relative/absolute references.",
        videoUrl: "#",
        publishedAt: "2026-06-09T12:00:00.000Z",
        access: "paid",
        duration: "1h 31m",
      },
    ],
    resources: demoResources.filter((item) => item.moduleId === "module-june-2026"),
    assessmentIds: [],
  },
  {
    id: "module-july-2026",
    programId: "program-theory",
    batchId: "batch-theory-2026",
    title: "July 2026",
    month: 7,
    year: 2026,
    access: "paid",
    status: "published",
    opensAt: "2026-07-01T00:00:00.000Z",
    closesAt: null,
    recordings: [
      {
        id: "rec-july-01",
        moduleId: "module-july-2026",
        title: "Programming — Algorithms and Flowcharts",
        description: "A practical introduction to algorithms, flowcharts and tracing logic.",
        videoUrl: "#",
        publishedAt: "2026-07-06T12:00:00.000Z",
        access: "paid",
        duration: "1h 48m",
      },
      {
        id: "rec-july-free",
        moduleId: "module-july-2026",
        title: "Free MCQ Technique Session",
        description: "A free session on managing time and eliminating incorrect MCQ options.",
        videoUrl: "#",
        publishedAt: "2026-07-11T12:00:00.000Z",
        access: "free",
        duration: "34m",
      },
    ],
    resources: demoResources.filter((item) => item.moduleId === "module-july-2026"),
    assessmentIds: ["assessment-diagnostic-01", "assessment-july-paper"],
  },
  {
    id: "module-august-2026",
    programId: "program-theory",
    batchId: "batch-theory-2026",
    title: "August 2026",
    month: 8,
    year: 2026,
    access: "paid",
    status: "upcoming",
    opensAt: "2026-08-01T00:00:00.000Z",
    closesAt: null,
    recordings: [],
    resources: [],
    assessmentIds: [],
  },
];

export const demoResults: ResultRecord[] = [
  {
    id: "result-01",
    assessmentId: "smart-ict-baseline",
    assessmentTitle: "Baseline Diagnostic",
    studentId: demoStudent.id,
    obtainedMarks: 47,
    totalMarks: 100,
    percentage: 47,
    source: "smart_ict",
    completedAt: "2026-03-14T12:00:00.000Z",
    status: "published",
    mcqMarks: 17,
    structuredMarks: 30,
  },
  {
    id: "result-02",
    assessmentId: "smart-ict-paper-01",
    assessmentTitle: "Monthly Paper 01",
    studentId: demoStudent.id,
    obtainedMarks: 56,
    totalMarks: 100,
    percentage: 56,
    source: "smart_ict",
    completedAt: "2026-04-18T12:00:00.000Z",
    status: "published",
    mcqMarks: 24,
    structuredMarks: 32,
  },
  {
    id: "result-03",
    assessmentId: "smart-ict-paper-02",
    assessmentTitle: "Monthly Paper 02",
    studentId: demoStudent.id,
    obtainedMarks: 64,
    totalMarks: 100,
    percentage: 64,
    source: "smart_ict",
    completedAt: "2026-05-23T12:00:00.000Z",
    status: "published",
    mcqMarks: 29,
    structuredMarks: 35,
  },
  {
    id: "result-04",
    assessmentId: "smart-ict-paper-03",
    assessmentTitle: "June Revision Paper",
    studentId: demoStudent.id,
    obtainedMarks: 71,
    totalMarks: 100,
    percentage: 71,
    source: "smart_ict",
    completedAt: "2026-06-27T12:00:00.000Z",
    status: "published",
    mcqMarks: 34,
    structuredMarks: 37,
  },
  {
    id: "result-school-01",
    assessmentId: "school-term-2025-3",
    assessmentTitle: "Grade 10 — Third Term",
    studentId: demoStudent.id,
    obtainedMarks: 45,
    totalMarks: 100,
    percentage: 45,
    source: "school",
    completedAt: "2025-12-10T12:00:00.000Z",
    status: "published",
  },
  {
    id: "result-school-02",
    assessmentId: "school-term-2026-1",
    assessmentTitle: "Grade 11 — First Term",
    studentId: demoStudent.id,
    obtainedMarks: 52,
    totalMarks: 100,
    percentage: 52,
    source: "school",
    completedAt: "2026-04-04T12:00:00.000Z",
    status: "published",
  },
  {
    id: "result-school-03",
    assessmentId: "school-term-2026-2",
    assessmentTitle: "Grade 11 — Second Term",
    studentId: demoStudent.id,
    obtainedMarks: 63,
    totalMarks: 100,
    percentage: 63,
    source: "school",
    completedAt: "2026-07-08T12:00:00.000Z",
    status: "published",
  },
];

export const demoPayments: PaymentRecord[] = [
  {
    id: "payment-may",
    studentId: demoStudent.id,
    programId: "program-theory",
    batchId: "batch-theory-2026",
    billingMonth: "2026-05-01",
    amount: 2400,
    status: "paid",
    paidAt: "2026-05-03T08:00:00.000Z",
  },
  {
    id: "payment-june",
    studentId: demoStudent.id,
    programId: "program-theory",
    batchId: "batch-theory-2026",
    billingMonth: "2026-06-01",
    amount: 2400,
    status: "paid",
    paidAt: "2026-06-05T08:00:00.000Z",
  },
  {
    id: "payment-july",
    studentId: demoStudent.id,
    programId: "program-theory",
    batchId: "batch-theory-2026",
    billingMonth: "2026-07-01",
    amount: 2400,
    status: "paid",
    paidAt: "2026-07-04T08:00:00.000Z",
  },
  {
    id: "payment-august",
    studentId: demoStudent.id,
    programId: "program-theory",
    batchId: "batch-theory-2026",
    billingMonth: "2026-08-01",
    amount: 2400,
    status: "unpaid",
    paidAt: null,
  },
];

export const demoTestimonials: Testimonial[] = [
  {
    id: "testimonial-01",
    studentName: "Student feedback",
    programName: "O/L ICT",
    quote: "The explanations are clear, and the online papers make it easy to see whether my marks are actually improving.",
    resultLabel: "Improved confidence",
    isPublished: true,
  },
  {
    id: "testimonial-02",
    studentName: "Parent feedback",
    programName: "Smart ICT",
    quote: "The personalised guidance and regular updates helped us understand what needed more attention before the examination.",
    resultLabel: "Structured guidance",
    isPublished: true,
  },
  {
    id: "testimonial-03",
    studentName: "Revision student",
    programName: "Rapid Revision",
    quote: "The revision was organised around questions, memory methods and exam technique instead of only repeating the textbook.",
    resultLabel: "Exam-ready practice",
    isPublished: true,
  },
];

export const demoDashboardData: DashboardData = {
  student: demoStudent,
  programs: demoPrograms.filter((program) => demoStudent.programIds.includes(program.id)),
  modules: demoModules,
  resources: demoResources,
  assessments: demoAssessments,
  results: demoResults,
  payments: demoPayments,
};
