export const PUBLIC_CONTENT_DEFAULTS = {
  hero_eyebrow: "Randinu Jayaratne | Smart ICT",
  hero_title: "Learn ICT smarter.",
  hero_highlight: "Build real confidence.",
  hero_description: "Grade 10 and Grade 11 ICT education with clear teaching, practical learning, smart revision and one connected LMS built around each student's progress.",
  hero_image_url: "/randinu-portrait.jpg",
  programs_kicker: "CURRENT PROGRAMS",
  programs_title: "Choose the journey that matches your exam year.",
  programs_description: "Grade 10 and Grade 11 learning with class content, resources, assessments and progress in one place.",
  about_kicker: "ABOUT THE TEACHER",
  about_title: "Learning with Randinu Jayaratne",
  about_lead: "Smart ICT is built around clear communication, student-focused guidance and practical understanding.",
  about_body: "Randinu brings leadership, public-speaking and ICT competition experience together with continuing legal studies and a strong interest in technology and digital transformation.",
  about_image_url: "/ol-theory-poster.jpg",
  why_kicker: "WHY SMART ICT",
  why_title: "A smarter class is more than a video and a PDF.",
  why_description: "Teaching, revision, resources and assessments work together as one learning system.",
  lms_kicker: "THE SMART ICT LMS",
  lms_title: "Your class, resources, assessments and progress - connected.",
  lms_description: "Students register with a phone number, request verification and receive teacher-approved access.",
  reviews_kicker: "STUDENT REVIEWS",
  reviews_title: "What students say about Smart ICT.",
  reviews_description: "Only teacher-approved reviews appear on the public website.",
  faq_kicker: "FREQUENTLY ASKED QUESTIONS",
  faq_title: "What you need to know before joining.",
  faq_description: "Registration, verification, payments and LMS access explained simply.",
  contact_kicker: "READY TO GET STARTED?",
  contact_title: "Join the Smart ICT learning journey.",
} as const;

export type PublicContentKey = keyof typeof PUBLIC_CONTENT_DEFAULTS;
