import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, FileCheck2 } from "lucide-react";
import { AssessmentPlayer } from "@/components/assessment-player";
import { getAssessmentForStudent, getStudentDashboardData } from "@/lib/data";
import { isSupabaseConfigured } from "@/lib/env";
import { canOpenAssessment } from "@/lib/access";

export default async function AssessmentPage({params}:{params:Promise<{assessmentId:string}>}){const{assessmentId}=await params;const[data,assessment]=await Promise.all([getStudentDashboardData(),getAssessmentForStudent(assessmentId)]);if(!assessment)notFound();const monthlyModule=data.modules.find((item)=>item.id===assessment.moduleId);const allowed=canOpenAssessment(data.student,assessment,monthlyModule,data.payments);if(!allowed)return <div><Link href="/app/assessments" className="back-link"><ArrowLeft size={16}/>Back to assessments</Link><section className="locked-content-panel"><FileCheck2 size={30}/><div><h2>This assessment is not available to your account.</h2><p>It may be assigned to another program or batch, or require paid access to a monthly module.</p></div><Link href="/app/support" className="button button-primary">Contact support</Link></section></div>;if(assessment.delivery==="offline")return <div><Link href="/app/assessments" className="back-link"><ArrowLeft size={16}/>Back to assessments</Link><section className="assessment-start-card"><div className="assessment-start-icon"><FileCheck2 size={38}/></div><span className="section-kicker">OFFLINE ASSESSMENT</span><h1>{assessment.title}</h1><p>{assessment.description}</p><div className="assessment-instructions"><strong>How this works</strong><p>This paper is completed outside the LMS. Once the teacher uploads and publishes your mark, it will appear in Results and your progress graphs.</p></div><Link href="/app/results" className="button button-primary">View published results</Link></section></div>;return <div><Link href="/app/assessments" className="back-link"><ArrowLeft size={16}/>Back to assessments</Link><AssessmentPlayer assessment={assessment} demoMode={!isSupabaseConfigured()}/></div>}
